<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateIconsTable extends Migration
{
    /**
     * Run the migrations.s
     *
     * @return void
     */
    public function up()
    {
        Schema::create('icons', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';

            $table->increments('id');
            $table->string('name', 50);
            $table->string('group', 50);
            $table->integer('status')->default(1);
            $table->timestamps();
        });

        DB::table('icons')->insert(['id'=>1, 'name'=>'account-logout', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>2, 'name'=>'action-redo', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>3, 'name'=>'action-undo', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>4, 'name'=>'align-center', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>5, 'name'=>'align-left', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>6, 'name'=>'align-right', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>7, 'name'=>'arrow-bottom', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>8, 'name'=>'arrow-left', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>9, 'name'=>'arrow-right', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>10, 'name'=>'arrow-top', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>11, 'name'=>'ban', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>12, 'name'=>'bell', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>13, 'name'=>'bold', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>14, 'name'=>'bookmark', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>15, 'name'=>'briefcase', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>16, 'name'=>'british-pound', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>17, 'name'=>'brush', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>18, 'name'=>'calculator', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>19, 'name'=>'calendar', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>20, 'name'=>'cart', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>21, 'name'=>'chart', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>22, 'name'=>'check', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>23, 'name'=>'chevron-bottom', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>24, 'name'=>'chevron-left', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>25, 'name'=>'chevron-right', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>26, 'name'=>'chevron-top', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>27, 'name'=>'circle-check', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>28, 'name'=>'circle-x', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>29, 'name'=>'cloud', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>30, 'name'=>'cloud-download', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>31, 'name'=>'cloud-upload', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>32, 'name'=>'code', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>33, 'name'=>'cog', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>34, 'name'=>'comment-square', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>35, 'name'=>'credit-card', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>36, 'name'=>'cursor', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>37, 'name'=>'dashboard', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>38, 'name'=>'delete', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>39, 'name'=>'dollar', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>40, 'name'=>'drop', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>41, 'name'=>'envelope-closed', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>42, 'name'=>'envelope-letter', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>43, 'name'=>'envelope-open', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>44, 'name'=>'euro', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>45, 'name'=>'file', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>46, 'name'=>'globe', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>47, 'name'=>'graph', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>48, 'name'=>'home', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>49, 'name'=>'inbox', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>50, 'name'=>'info', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>51, 'name'=>'italic', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>52, 'name'=>'justify-center', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>53, 'name'=>'justify-left', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>54, 'name'=>'justify-right', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>55, 'name'=>'laptop', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>56, 'name'=>'layers', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>57, 'name'=>'lightbulb', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>59, 'name'=>'list', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>60, 'name'=>'location-pin', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>61, 'name'=>'lock-locked', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>62, 'name'=>'lock-unlocked', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>63, 'name'=>'magnifying-glass', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>64, 'name'=>'map', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>65, 'name'=>'monitor', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>66, 'name'=>'moon', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>67, 'name'=>'note', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>68, 'name'=>'options', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>69, 'name'=>'paperclip', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>70, 'name'=>'pencil', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>71, 'name'=>'people', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>72, 'name'=>'phone', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>73, 'name'=>'pie-chart', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>74, 'name'=>'print', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>75, 'name'=>'puzzle', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>76, 'name'=>'rss', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>77, 'name'=>'screen-desktop', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>78, 'name'=>'screen-smartphone', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>79, 'name'=>'settings', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>80, 'name'=>'share', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>81, 'name'=>'shield', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>82, 'name'=>'sort-ascending', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>83, 'name'=>'sort-descending', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>84, 'name'=>'speech', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>85, 'name'=>'speedometer', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>86, 'name'=>'star', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>87, 'name'=>'sun', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>88, 'name'=>'tablet', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>89, 'name'=>'tags', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>90, 'name'=>'task', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>91, 'name'=>'thumb-down', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>92, 'name'=>'thumb-up', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>93, 'name'=>'trash', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>94, 'name'=>'underline', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>95, 'name'=>'user', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>96, 'name'=>'user-female', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>97, 'name'=>'user-follow', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>98, 'name'=>'user-unfollow', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>99, 'name'=>'wrench', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>100, 'name'=>'yen', 'group'=>'icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>101, 'name'=>'flag-icon-ad', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>102, 'name'=>'flag-icon-ae', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>103, 'name'=>'flag-icon-af', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>104, 'name'=>'flag-icon-ag', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>105, 'name'=>'flag-icon-ai', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>106, 'name'=>'flag-icon-al', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>107, 'name'=>'flag-icon-am', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>108, 'name'=>'flag-icon-ao', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>109, 'name'=>'flag-icon-aq', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>110, 'name'=>'flag-icon-ar', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>111, 'name'=>'flag-icon-as', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>112, 'name'=>'flag-icon-at', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>113, 'name'=>'flag-icon-au', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>114, 'name'=>'flag-icon-aw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>115, 'name'=>'flag-icon-ax', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>116, 'name'=>'flag-icon-az', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>117, 'name'=>'flag-icon-ba', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>118, 'name'=>'flag-icon-bb', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>119, 'name'=>'flag-icon-bd', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>120, 'name'=>'flag-icon-be', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>121, 'name'=>'flag-icon-bf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>122, 'name'=>'flag-icon-bg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>123, 'name'=>'flag-icon-bh', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>124, 'name'=>'flag-icon-bi', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>125, 'name'=>'flag-icon-bj', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>126, 'name'=>'flag-icon-bl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>127, 'name'=>'flag-icon-bm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>128, 'name'=>'flag-icon-bn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>129, 'name'=>'flag-icon-bo', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>130, 'name'=>'flag-icon-bq', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>131, 'name'=>'flag-icon-br', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>132, 'name'=>'flag-icon-bs', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>133, 'name'=>'flag-icon-bt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>134, 'name'=>'flag-icon-bv', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>135, 'name'=>'flag-icon-bw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>136, 'name'=>'flag-icon-by', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>137, 'name'=>'flag-icon-bz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>138, 'name'=>'flag-icon-ca', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>139, 'name'=>'flag-icon-cc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>140, 'name'=>'flag-icon-cd', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>141, 'name'=>'flag-icon-cf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>142, 'name'=>'flag-icon-cg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>143, 'name'=>'flag-icon-ch', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>144, 'name'=>'flag-icon-ci', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>145, 'name'=>'flag-icon-ck', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>146, 'name'=>'flag-icon-cl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>147, 'name'=>'flag-icon-cm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>148, 'name'=>'flag-icon-cn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>149, 'name'=>'flag-icon-co', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>150, 'name'=>'flag-icon-cr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>151, 'name'=>'flag-icon-cu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>152, 'name'=>'flag-icon-cv', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>153, 'name'=>'flag-icon-cw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>154, 'name'=>'flag-icon-cx', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>155, 'name'=>'flag-icon-cy', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>156, 'name'=>'flag-icon-cz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>157, 'name'=>'flag-icon-de', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>158, 'name'=>'flag-icon-dj', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>159, 'name'=>'flag-icon-dk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>160, 'name'=>'flag-icon-dm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>161, 'name'=>'flag-icon-do', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>162, 'name'=>'flag-icon-dz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>163, 'name'=>'flag-icon-ec', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>164, 'name'=>'flag-icon-ee', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>165, 'name'=>'flag-icon-eg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>166, 'name'=>'flag-icon-eh', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>167, 'name'=>'flag-icon-er', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>168, 'name'=>'flag-icon-es', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>169, 'name'=>'flag-icon-et', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>170, 'name'=>'flag-icon-fi', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>171, 'name'=>'flag-icon-fj', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>172, 'name'=>'flag-icon-fk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>173, 'name'=>'flag-icon-fm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>174, 'name'=>'flag-icon-fo', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>175, 'name'=>'flag-icon-fr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>176, 'name'=>'flag-icon-ga', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>177, 'name'=>'flag-icon-gb', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>178, 'name'=>'flag-icon-gd', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>179, 'name'=>'flag-icon-ge', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>180, 'name'=>'flag-icon-gf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>181, 'name'=>'flag-icon-gg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>182, 'name'=>'flag-icon-gh', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>183, 'name'=>'flag-icon-gi', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>184, 'name'=>'flag-icon-gl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>185, 'name'=>'flag-icon-gm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>186, 'name'=>'flag-icon-gn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>187, 'name'=>'flag-icon-gp', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>188, 'name'=>'flag-icon-gq', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>189, 'name'=>'flag-icon-gr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>190, 'name'=>'flag-icon-gs', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>191, 'name'=>'flag-icon-gt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>192, 'name'=>'flag-icon-gu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>193, 'name'=>'flag-icon-gw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>194, 'name'=>'flag-icon-gy', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>195, 'name'=>'flag-icon-hk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>196, 'name'=>'flag-icon-hm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>197, 'name'=>'flag-icon-hn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>198, 'name'=>'flag-icon-hr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>199, 'name'=>'flag-icon-ht', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>200, 'name'=>'flag-icon-hu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>201, 'name'=>'flag-icon-id', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>202, 'name'=>'flag-icon-ie', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>203, 'name'=>'flag-icon-il', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>204, 'name'=>'flag-icon-im', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>205, 'name'=>'flag-icon-in', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>206, 'name'=>'flag-icon-io', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>207, 'name'=>'flag-icon-iq', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>208, 'name'=>'flag-icon-ir', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>209, 'name'=>'flag-icon-is', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>210, 'name'=>'flag-icon-it', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>211, 'name'=>'flag-icon-je', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>212, 'name'=>'flag-icon-jm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>213, 'name'=>'flag-icon-jo', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>214, 'name'=>'flag-icon-jp', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>215, 'name'=>'flag-icon-ke', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>216, 'name'=>'flag-icon-kg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>217, 'name'=>'flag-icon-kh', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>218, 'name'=>'flag-icon-ki', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>219, 'name'=>'flag-icon-km', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>220, 'name'=>'flag-icon-kn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>221, 'name'=>'flag-icon-kp', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>222, 'name'=>'flag-icon-kr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>223, 'name'=>'flag-icon-kw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>224, 'name'=>'flag-icon-ky', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>225, 'name'=>'flag-icon-kz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>226, 'name'=>'flag-icon-la', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>227, 'name'=>'flag-icon-lb', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>228, 'name'=>'flag-icon-lc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>229, 'name'=>'flag-icon-li', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>230, 'name'=>'flag-icon-lk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>231, 'name'=>'flag-icon-lr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>232, 'name'=>'flag-icon-ls', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>233, 'name'=>'flag-icon-lt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>234, 'name'=>'flag-icon-lu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>235, 'name'=>'flag-icon-lv', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>236, 'name'=>'flag-icon-ly', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>237, 'name'=>'flag-icon-ma', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>238, 'name'=>'flag-icon-mc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>239, 'name'=>'flag-icon-md', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>240, 'name'=>'flag-icon-me', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>241, 'name'=>'flag-icon-mf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>242, 'name'=>'flag-icon-mg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>243, 'name'=>'flag-icon-mh', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>244, 'name'=>'flag-icon-mk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>245, 'name'=>'flag-icon-ml', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>246, 'name'=>'flag-icon-mm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>247, 'name'=>'flag-icon-mn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>248, 'name'=>'flag-icon-mo', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>249, 'name'=>'flag-icon-mp', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>250, 'name'=>'flag-icon-mq', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>251, 'name'=>'flag-icon-mr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>252, 'name'=>'flag-icon-ms', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>253, 'name'=>'flag-icon-mt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>254, 'name'=>'flag-icon-mu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>255, 'name'=>'flag-icon-mv', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>256, 'name'=>'flag-icon-mw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>257, 'name'=>'flag-icon-mx', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>258, 'name'=>'flag-icon-my', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>259, 'name'=>'flag-icon-mz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>260, 'name'=>'flag-icon-na', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>261, 'name'=>'flag-icon-nc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>262, 'name'=>'flag-icon-ne', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>263, 'name'=>'flag-icon-nf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>264, 'name'=>'flag-icon-ng', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>265, 'name'=>'flag-icon-ni', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>266, 'name'=>'flag-icon-nl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>267, 'name'=>'flag-icon-no', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>268, 'name'=>'flag-icon-np', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>269, 'name'=>'flag-icon-nr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>270, 'name'=>'flag-icon-nu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>271, 'name'=>'flag-icon-nz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>272, 'name'=>'flag-icon-om', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>273, 'name'=>'flag-icon-pa', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>274, 'name'=>'flag-icon-pe', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>275, 'name'=>'flag-icon-pf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>276, 'name'=>'flag-icon-pg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>277, 'name'=>'flag-icon-ph', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>278, 'name'=>'flag-icon-pk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>279, 'name'=>'flag-icon-pl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>280, 'name'=>'flag-icon-pm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>281, 'name'=>'flag-icon-pn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>282, 'name'=>'flag-icon-pr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>283, 'name'=>'flag-icon-ps', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>284, 'name'=>'flag-icon-pt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>285, 'name'=>'flag-icon-pw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>286, 'name'=>'flag-icon-py', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>287, 'name'=>'flag-icon-qa', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>288, 'name'=>'flag-icon-re', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>289, 'name'=>'flag-icon-ro', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>290, 'name'=>'flag-icon-rs', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>291, 'name'=>'flag-icon-ru', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>292, 'name'=>'flag-icon-rw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>293, 'name'=>'flag-icon-sa', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>294, 'name'=>'flag-icon-sb', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>295, 'name'=>'flag-icon-sc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>296, 'name'=>'flag-icon-sd', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>297, 'name'=>'flag-icon-se', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>298, 'name'=>'flag-icon-sg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>299, 'name'=>'flag-icon-sh', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>300, 'name'=>'flag-icon-si', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>301, 'name'=>'flag-icon-sj', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>302, 'name'=>'flag-icon-sk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>303, 'name'=>'flag-icon-sl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>304, 'name'=>'flag-icon-sm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>305, 'name'=>'flag-icon-sn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>306, 'name'=>'flag-icon-so', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>307, 'name'=>'flag-icon-sr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>308, 'name'=>'flag-icon-ss', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>309, 'name'=>'flag-icon-st', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>310, 'name'=>'flag-icon-sv', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>311, 'name'=>'flag-icon-sx', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>312, 'name'=>'flag-icon-sy', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>313, 'name'=>'flag-icon-sz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>314, 'name'=>'flag-icon-tc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>315, 'name'=>'flag-icon-td', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>316, 'name'=>'flag-icon-tf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>317, 'name'=>'flag-icon-tg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>318, 'name'=>'flag-icon-th', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>319, 'name'=>'flag-icon-tj', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>320, 'name'=>'flag-icon-tk', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>321, 'name'=>'flag-icon-tl', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>322, 'name'=>'flag-icon-tm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>323, 'name'=>'flag-icon-to', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>324, 'name'=>'flag-icon-tr', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>325, 'name'=>'flag-icon-tt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>326, 'name'=>'flag-icon-tv', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>327, 'name'=>'flag-icon-tw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>328, 'name'=>'flag-icon-tz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>329, 'name'=>'flag-icon-ua', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>330, 'name'=>'flag-icon-ug', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>331, 'name'=>'flag-icon-um', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>332, 'name'=>'flag-icon-us', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>333, 'name'=>'flag-icon-uy', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>334, 'name'=>'flag-icon-uz', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>335, 'name'=>'flag-icon-va', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>336, 'name'=>'flag-icon-vc', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>337, 'name'=>'flag-icon-ve', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>338, 'name'=>'flag-icon-vg', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>339, 'name'=>'flag-icon-vi', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>340, 'name'=>'flag-icon-vn', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>341, 'name'=>'flag-icon-vu', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>342, 'name'=>'flag-icon-wf', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>343, 'name'=>'flag-icon-ws', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>344, 'name'=>'flag-icon-ye', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>345, 'name'=>'flag-icon-yt', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>346, 'name'=>'flag-icon-za', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>347, 'name'=>'flag-icon-zm', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>348, 'name'=>'flag-icon-zw', 'group'=>'flag-icon', 'status'=>1]);
        DB::table('icons')->insert(['id'=>349, 'name'=>'address-book', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>350, 'name'=>'address-book-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>351, 'name'=>'address-card', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>352, 'name'=>'address-card-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>353, 'name'=>'bandcamp', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>354, 'name'=>'bath', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>355, 'name'=>'bathtub', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>356, 'name'=>'drivers-license', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>357, 'name'=>'drivers-license-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>358, 'name'=>'eercast', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>359, 'name'=>'envelope-open', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>360, 'name'=>'envelope-open-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>361, 'name'=>'etsy', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>362, 'name'=>'free-code-camp', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>363, 'name'=>'grav', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>364, 'name'=>'handshake-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>365, 'name'=>'id-badge', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>366, 'name'=>'id-card', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>367, 'name'=>'id-card-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>368, 'name'=>'imdb', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>369, 'name'=>'linode', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>370, 'name'=>'meetup', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>371, 'name'=>'meetup', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>372, 'name'=>'podcast', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>373, 'name'=>'quora', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>374, 'name'=>'ravelry', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>375, 'name'=>'s15', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>376, 'name'=>'shower', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>377, 'name'=>'snowflake-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>378, 'name'=>'superpowers', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>379, 'name'=>'telegram', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>380, 'name'=>'thermometer', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>381, 'name'=>'thermometer-0', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>382, 'name'=>'thermometer-1', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>383, 'name'=>'thermometer-2', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>384, 'name'=>'thermometer-3', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>385, 'name'=>'thermometer-4', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>386, 'name'=>'thermometer-empty', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>387, 'name'=>'thermometer-full', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>388, 'name'=>'thermometer-half', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>389, 'name'=>'thermometer-quarter', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>390, 'name'=>'thermometer-three-quarters', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>391, 'name'=>'times-rectangle', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>392, 'name'=>'times-rectangle-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>393, 'name'=>'user-circle', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>394, 'name'=>'user-circle-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>395, 'name'=>'user-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>396, 'name'=>'vcard', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>397, 'name'=>'vcard-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>398, 'name'=>'window-close', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>399, 'name'=>'window-close-o', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>400, 'name'=>'window-maximize', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>401, 'name'=>'window-minimize', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>402, 'name'=>'window-restore', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>403, 'name'=>'wpexplorer', 'group'=>'fa', 'status'=>1]);
        DB::table('icons')->insert(['id'=>404, 'name'=>'fa-bluetooth', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>405, 'name'=>'fa-bluetooth-b', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>406, 'name'=>'fa-codiepie', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>407, 'name'=>'fa-credit-card-alt', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>408, 'name'=>'fa-edge', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>409, 'name'=>'fa-fort-awesome', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>410, 'name'=>'fa-hashtag', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>411, 'name'=>'fa-mixcloud', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>412, 'name'=>'fa-modx', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>413, 'name'=>'fa-pause-circle', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>414, 'name'=>'fa-pause-circle-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>415, 'name'=>'fa-percent', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>416, 'name'=>'fa-product-hunt', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>417, 'name'=>'fa-reddit-alien', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>418, 'name'=>'fa-scribd', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>419, 'name'=>'fa-shopping-bag', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>420, 'name'=>'fa-shopping-basket', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>421, 'name'=>'fa-stop-circle', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>422, 'name'=>'fa-stop-circle-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>423, 'name'=>'fa-usb', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>424, 'name'=>'fa-adjust', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>425, 'name'=>'fa-anchor', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>426, 'name'=>'fa-archive', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>427, 'name'=>'fa-area-chart', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>428, 'name'=>'fa-arrows', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>429, 'name'=>'fa-arrows-h', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>430, 'name'=>'fa-arrows-v', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>431, 'name'=>'fa-asterisk', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>432, 'name'=>'fa-at', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>433, 'name'=>'fa-automobile', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>434, 'name'=>'fa-balance-scale', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>435, 'name'=>'fa-ban', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>436, 'name'=>'fa-bank', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>437, 'name'=>'fa-bar-chart', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>438, 'name'=>'fa-bar-chart-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>439, 'name'=>'fa-barcode', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>440, 'name'=>'fa-bars', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>441, 'name'=>'fa-battery-0', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>442, 'name'=>'fa-battery-1', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>443, 'name'=>'fa-battery-2', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>444, 'name'=>'fa-battery-3', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>445, 'name'=>'fa-battery-4', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>446, 'name'=>'fa-battery-empty', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>447, 'name'=>'fa-battery-full', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>448, 'name'=>'fa-battery-half', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>449, 'name'=>'fa-battery-quarter', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>450, 'name'=>'fa-battery-three-quarters', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>451, 'name'=>'fa-bed', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>452, 'name'=>'fa-beer', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>453, 'name'=>'fa-bell', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>454, 'name'=>'fa-bell-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>455, 'name'=>'fa-bell-slash', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>456, 'name'=>'fa-bell-slash-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>457, 'name'=>'fa-bicycle', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>458, 'name'=>'fa-binoculars', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>459, 'name'=>'fa-birthday-cake', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>460, 'name'=>'fa-bolt', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>461, 'name'=>'fa-bomb', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>462, 'name'=>'fa-book', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>463, 'name'=>'fa-bookmark', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>464, 'name'=>'fa-bookmark-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>465, 'name'=>'fa-briefcase', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>466, 'name'=>'fa-bug', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>467, 'name'=>'fa-building', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>468, 'name'=>'fa-building-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>469, 'name'=>'fa-bullhorn', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>470, 'name'=>'fa-bullseye', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>471, 'name'=>'fa-bus', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>472, 'name'=>'fa-cab', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>473, 'name'=>'fa-calculator', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>474, 'name'=>'fa-calendar', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>475, 'name'=>'fa-calendar-check-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>476, 'name'=>'fa-calendar-minus-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>477, 'name'=>'fa-calendar-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>478, 'name'=>'fa-calendar-plus-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>479, 'name'=>'fa-calendar-times-o', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>480, 'name'=>'fa-camera', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>481, 'name'=>'fa-camera-retro', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);
        DB::table('icons')->insert(['id'=>482, 'name'=>'fa-car', 'group'=>'fa', 'status'=>1, 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s')]);

    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('icons');
    }
}
